import puppeteer from 'puppeteer';

interface ReportData {
  applicationId: string;
  businessName: string;
  businessType: string;
  auditorName: string;
  date: string;
  totalScore: number;
  recommendation: string;
  checklist: any[];
}

export const generateAuditReportPDF = async (data: ReportData): Promise<Buffer> => {
  // Generate HTML for the report
  const checklistHtml = data.checklist.map(item => `
    <div style="margin-bottom: 20px; padding: 15px; border: 1px solid #e2e8f0; border-radius: 8px;">
      <div style="display: flex; justify-content: space-between; align-items: start;">
        <div>
          <h4 style="margin: 0 0 5px 0; color: #0f172a;">${item.criterion}</h4>
          <span style="font-size: 12px; color: #64748b; text-transform: uppercase;">Section: ${item.section}</span>
          ${item.isCritical ? `<span style="font-size: 10px; background: #ef4444; color: white; padding: 2px 6px; border-radius: 4px; margin-left: 8px;">CRITICAL</span>` : ''}
        </div>
        <div style="font-size: 18px; font-weight: bold; color: ${item.score === 0 ? '#ef4444' : '#10b981'};">
          ${item.score ?? 'N/A'} / 5
        </div>
      </div>
      
      ${item.comment ? `
        <div style="margin-top: 10px; padding: 10px; background: #f8fafc; border-left: 3px solid #cbd5e1; font-size: 14px; color: #334155;">
          <strong>Auditor Comment:</strong> ${item.comment}
        </div>
      ` : ''}
    </div>
  `).join('');

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; line-height: 1.6; margin: 0; padding: 40px; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #0f172a; padding-bottom: 20px; }
        .header h1 { margin: 0; color: #0f172a; font-size: 28px; letter-spacing: 1px; text-transform: uppercase; }
        .header p { margin: 5px 0 0 0; color: #64748b; font-size: 14px; }
        .summary-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin-bottom: 40px; display: flex; flex-wrap: wrap; gap: 20px; }
        .summary-item { flex: 1; min-width: 200px; }
        .summary-item label { display: block; font-size: 12px; color: #64748b; text-transform: uppercase; font-weight: bold; margin-bottom: 4px; }
        .summary-item span { font-size: 16px; color: #0f172a; font-weight: 500; }
        .score-box { text-align: center; padding: 20px; background: ${data.totalScore >= 3.5 ? '#f0fdf4' : data.totalScore >= 2.5 ? '#fffbeb' : '#fef2f2'}; border: 1px solid ${data.totalScore >= 3.5 ? '#bbf7d0' : data.totalScore >= 2.5 ? '#fef08a' : '#fecaca'}; border-radius: 8px; margin-bottom: 40px; }
        .score-box h2 { margin: 0; font-size: 36px; color: ${data.totalScore >= 3.5 ? '#166534' : data.totalScore >= 2.5 ? '#854d0e' : '#991b1b'}; }
        .score-box p { margin: 5px 0 0 0; color: #64748b; font-size: 14px; text-transform: uppercase; font-weight: bold; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>AAHAR Audit Report</h1>
        <p>Official Inspection Results</p>
      </div>

      <div class="summary-box">
        <div class="summary-item">
          <label>Business Name</label>
          <span>${data.businessName}</span>
        </div>
        <div class="summary-item">
          <label>Application ID</label>
          <span>${data.applicationId}</span>
        </div>
        <div class="summary-item">
          <label>Date of Audit</label>
          <span>${data.date}</span>
        </div>
        <div class="summary-item">
          <label>Auditor Name</label>
          <span>${data.auditorName}</span>
        </div>
        <div class="summary-item">
          <label>Recommendation</label>
          <span style="text-transform: capitalize;">${data.recommendation.replace('_', ' ')}</span>
        </div>
      </div>

      <div class="score-box">
        <h2>${data.totalScore} / 5.0</h2>
        <p>Overall Audit Score</p>
      </div>

      <h3 style="color: #0f172a; border-bottom: 1px solid #e2e8f0; padding-bottom: 10px; margin-bottom: 20px;">Detailed Findings</h3>
      
      ${checklistHtml}

      <div class="footer">
        Generated by AAHAR Private Limited Company • ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;

  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  });
  
  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: 'networkidle0' });
  
  const pdfBuffer = await page.pdf({
    format: 'A4',
    printBackground: true,
    margin: { top: '20px', bottom: '20px' }
  });
  
  await browser.close();
  
  // Puppeteer returns a Uint8Array, we convert to Buffer
  return Buffer.from(pdfBuffer);
};
